__precompile__()
const global ZERO_VAL = 1e-15
include("crm_utils.jl")
include("plots_util.jl")
include("read_netlib_MPS.jl")
include("MAP.jl")
include("DRM.jl")
include("SPM.jl")
include("CRM.jl")
include("CentCRM.jl")